### ISSUE TITLE
add helm chart to Artifacthub

### ISSUE THREAD

**Issue by M0NsTeRRR** [Stirling-Tools/Stirling-PDF-chart#2]
Artifacthub is a CNCF project is a web-based application that enables finding, installing, and publishing packages. It would help new users to find this helm chart and will give visibility to the project.

1) Create an account https://artifacthub.io
2) Register this repository
3) Create `artifacthub-repo.yml` in `gh-pages` branch with :
```
repositoryID: <REPOSITORY ID>
owners:
  - name: <Your name>
    email: <Your email>
```

Documentation : https://artifacthub.io/docs/topics/repositories/#verified-publisher

@Frooodle
